# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: asahi-installer.spec
files_to_sync:
  - asahi-installer.spec
  - .packit.yaml

actions:
  # Fetch the specfile from Rawhide, disable rpmautospec and download the
  # missing libffi tarball from the lookaside
  post-upstream-clone: "bash -c \"curl -s https://src.fedoraproject.org/rpms/asahi-installer/raw/main/f/asahi-installer.spec | sed -e '/^%autochangelog$/d' > asahi-installer.spec && curl -s --remote-name https://src.fedoraproject.org/repo/pkgs/asahi-installer/libffi-3.5.2-macos.tar.gz/sha512/1cc3e7807d6ad434b3e399fbbed63a6d4347c1eb707a03cd9c7e067304403c04be3ff4a70b6e06b5857cf1ea16fc628d83815fa3b8b7c5674d552b690b630297/libffi-3.5.2-macos.tar.gz\""

srpm_build_deps:
  - bash
  - curl
  - sed

jobs:
- job: copr_build
  trigger: commit
  owner: "@asahi"
  project: packit-builds
  targets:
    - fedora-all-aarch64
    - fedora-rawhide-i386
    - fedora-rawhide-ppc64le
    - fedora-rawhide-x86_64

- job: copr_build
  trigger: pull_request
  owner: "@asahi"
  project: packit-builds
  targets:
    - fedora-all-aarch64
    - fedora-rawhide-i386
    - fedora-rawhide-ppc64le
    - fedora-rawhide-x86_64
